### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [pruzko/hakuin#14]
Could you please tag the source? This allows distributions to get the complete source from GitHub iif they want.

Thanks

**Comment by pruzko** [comment]
I'm not that familiar with GH versioning, but I assume you want to tag a _stable_ version so that it can be packaged for linux distros (correct me if I'm wrong).

As of now, there is no stable version. All the versions available on pypi are 0.0.*. This is because:
1) I am still improving the design and refactoring the code,
2) the API changes considerably, and
3) some parts of the code are not tested yet.

The roadmap to the first stable version is roughly:
1) completing the above,
2) adding optimizations for non-textual types (currently in progress), and
3) installation testing.

Once all of this is done, I'll release the first stable version and add GH versioning. Would that do?

**Comment by fabaff** [comment]
Somebody mentioned to me that [0.1.10](https://github.com/pruzko/hakuin/blob/main/pyproject.toml#L8) is available on [PyPI](https://pypi.org/project/hakuin/) while the [Nixpkgs package](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=hakuin) is using the source and ships the state from March.

No `stable` needed, just `git tag -a x.y.z && git push origin x.y.z` every time a new release is published on PyPI :wink:

**Comment by pruzko** [comment]
Be it, I added the [tag](https://github.com/pruzko/hakuin/releases/tag/0.1.10).
I was oblivious to the Nix packages, thanks :)
